### Get all notes
GET http://localhost:8080/notes


### Get note by ID
GET http://localhost:8080/notes/7


### Create note
POST http://localhost:8080/post
Content-Type: application/json

{
  "title": "React",
  "content": "Struggling to become React Dev"
}


### Update note
PUT http://localhost:8080/notes/7
Content-Type: application/json

{
  "title": "Spring",
  "content": "Became Spring God"
}


### Delete note
DELETE http://localhost:8080/notes/2