### Get all notes
GET http://localhost:8080/notes


### Get note by ID
GET http://localhost:8080/notes/2


### Create note
POST http://localhost:8080/post
Content-Type: application/json

{
  "title": "GCP",
  "content": "Became GCP God"
}


### Update note
PUT http://localhost:8080/notes/5
Content-Type: application/json

{
  "title": "AWS",
  "content": "Became AWS God"
}


### Delete note
DELETE http://localhost:8080/notes/5