spring.application.name=notemaker

spring.datasource.url=jdbc:postgresql://localhost:5432/notemaker
spring.datasource.username=roysid
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
